-- ============================================================================
-- PLACE YOUR SERVICE (PYS) — MIGRATION 20261009010000
-- Seed Softwear Data.xlsx Master Models and Model Variants
-- Excludes Conflicting Models: AKABISHI RWM-HE13SG & EWY-HA18SG
-- ============================================================================

-- 1. Upsert Parent AC Models
WITH brand_map AS (
  SELECT id, code FROM public.ac_brands
),
model_seed(brand_code, model_number, ac_type, technology, capacity_tons, rating) AS (
  VALUES
  ('MITSUBISHI_HEAVY', 'SRK / DXK 5CAPDA - W', 'Split AC', 'Non Inverter', 1.20, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 18CAPDA - W', 'Split AC', 'Non Inverter', 1.50, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 20CAPDA - W', 'Split AC', 'Non Inverter', 1.60, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 25CAPDA - W', 'Split AC', 'Non Inverter', 2.15, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 13YAMDA - W', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 18YAMDA - W', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 21YAMDA - W', 'Split AC', 'Inverter', 1.75, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 27YAMDA - W', 'Split AC', 'Inverter', 2.25, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK13CRS-S6', 'Split AC', 'Non Inverter', 1.10, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK15CXS-W6', 'Split AC', 'Non Inverter', 1.30, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK20CXS-W6', 'Split AC', 'Non Inverter', 1.60, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK20CSS-S6 / A', 'Split AC', 'Non Inverter', 1.60, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK24CW-S6', 'Split AC', 'Non Inverter', 1.95, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK25CWX-S6', 'Split AC', 'Non Inverter', 1.95, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK25CSS-S6 / A', 'Split AC', 'Non Inverter', 2.20, '2 Star'),
  ('MITSUBISHI_HEAVY', 'SRK13YYM-W6', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK13YXS-W6', 'Split AC', 'Inverter', 1.10, '5 Star'),
  ('MITSUBISHI_HEAVY', 'SRK18YXP-W6', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('MITSUBISHI_HEAVY', 'SRK18YYM-W6', 'Split AC', 'Inverter', 1.60, '4 Star'),
  ('MITSUBISHI_HEAVY', 'SRK18YXS2-W6', 'Split AC', 'Inverter', 1.65, '5 Star'),
  ('MITSUBISHI_HEAVY', 'SRK20YYM-W6', 'Split AC', 'Inverter', 1.80, '5 Star'),
  ('MITSUBISHI_HEAVY', 'SRK24YYM-W6', 'Split AC', 'Inverter', 2.10, '4 Star'),
  ('MITSUBISHI_HEAVY', 'SRK24YVS-W6', 'Split AC', 'Inverter', 2.20, '5 Star'),
  ('MITSUBISHI_HEAVY', 'SRK100YA-W6', 'Split AC', 'Inverter', 3.00, '4 Star'),
  ('MITSUBISHI_HEAVY', 'SRK18YYS-W6 ( WIFII ENABLED )', 'Split AC', 'Inverter', 1.60, '5 Star'),
  ('MITSUBISHI_HEAVY', 'SRK24YYS-W6 ( WIFI ENABLED )', 'Split AC', 'Inverter', 2.20, '5 Star'),
  ('MITSUBISHI_HEAVY', 'SRK50ZS', 'Split AC', 'Inverter', 1.50, 'N/A'),
  ('MITSUBISHI_HEAVY', 'SRK71ZR', 'Split AC', 'Inverter', 2.10, 'N/A'),
  ('MITSUBISHI_HEAVY', 'SRK100ZR', 'Split AC', 'Inverter', 3.10, '4 Star'),
  ('DAIKIN', 'FTKM35XV', 'Split AC', 'Inverter', 1.00, '5 Star'),
  ('DAIKIN', 'FTKM50XV', 'Split AC', 'Inverter', 1.50, '5 Star'),
  ('DAIKIN', 'FTKM60XV', 'Split AC', 'Inverter', 1.80, '5 Star'),
  ('DAIKIN', 'FTKU35XV', 'Split AC', 'Inverter', 1.00, '5 Star'),
  ('DAIKIN', 'FTKU42XV', 'Split AC', 'Inverter', 1.20, '5 Star'),
  ('DAIKIN', 'FTKU50XV', 'Split AC', 'Inverter', 1.50, '5 Star'),
  ('DAIKIN', 'FTKL35XV', 'Split AC', 'Premium Series - Inverte', 1.00, '3 Star'),
  ('DAIKIN', 'FTKL50XV', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('DAIKIN', 'FTKL60XV', 'Split AC', 'Inverter', 1.80, '3 Star'),
  ('DAIKIN', 'FTKL71XV', 'Split AC', 'Inverter', 2.00, '3 Star'),
  ('DAIKIN', 'FTKL90XV', 'Split AC', 'Inverter', 2.60, '3 Star'),
  ('DAIKIN', 'FTKC35XV', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('DAIKIN', 'FTKC48XV', 'Split AC', 'Inverter', 1.40, '3 Star'),
  ('DAIKIN', 'FTKC50XV', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('DAIKIN', 'FTQ28XV', 'Split AC', 'Non Inverter', 0.80, '2 Star'),
  ('DAIKIN', 'FTQ30XV', 'Split AC', 'Non Inverter', 0.90, '2 Star'),
  ('DAIKIN', 'FTQ35XV', 'Split AC', 'Non Inverter', 1.00, '2 Star'),
  ('DAIKIN', 'FTQ50XV', 'Split AC', 'Non Inverter', 1.50, '2 Star'),
  ('VOLTAS', 'SAC122 FS EMERALD', 'Split AC', 'Non Inverter', 1.00, '2 Star'),
  ('VOLTAS', 'SAC182 FS PRISM', 'Split AC', 'Non Inverter', 1.50, '2 Star'),
  ('VOLTAS', 'SAC242 PLUSH', 'Split AC', 'Non Inverter', 2.00, '2 Star'),
  ('VOLTAS', 'SAC 123INV VECTRA EMARALD / ELEGANT', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('VOLTAS', 'SAC 183INV VECTRA ZEN / ZENITH SILVER', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('VOLTAS', 'SAC 183INV VERTIS ZENITH GOLD', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('VOLTAS', 'SAC243 INV VECTRA PLUSH', 'Split AC', 'Inverter', 2.00, '3 Star'),
  ('VOLTAS', 'SAC 125V VECTRA', 'Split AC', 'Inverter', 1.00, '5 Star'),
  ('VOLTAS', 'SAC 185INV VERTIS ELITE', 'Split AC', 'Inverter', 1.50, '5 Star'),
  ('VOLTAS', 'SAC 245 INV VECTRA PLUSH', 'Split AC', 'Inverter', 2.00, '5 Star'),
  ('VOLTAS', 'WAC 122 FS PLATINA-1 ( 22 X 15 )', 'Window AC', 'Non Inverter', 1.00, '2 Star'),
  ('VOLTAS', 'WAC 182 FS PEARL / ELITE ( 26 X 17 )', 'Window AC', 'Non Inverter', 1.50, '2 Star'),
  ('VOLTAS', 'WAC 241 FS PLUS (26 X 17)', 'Window AC', 'Non Inverter', 2.00, '1 Star'),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ13VF+MU-AGZ13VF', 'Split AC', 'Non Inverter', 1.00, '2 Star'),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ18VF+MU-AGZ18VF', 'Split AC', 'Non Inverter', 1.50, '2 Star'),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ19VF+MU-AGZ19VF', 'Split AC', 'Non Inverter', 1.60, '2 Star'),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ24VF+MU-AGZ24VF', 'Split AC', 'Non Inverter', 1.90, '2 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ13VF+MSY-AMZ13VF', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ18VF+MUY-AMZ18VF', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ22VF+MUY-AMZ22VF', 'Split AC', 'Inverter', 1.90, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ24VF+MUY-AMZ24VF', 'Split AC', 'Inverter', 2.00, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-JZ13VF+MUY-JZ13VF', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-JZ18VF+MUY-JZ18VF', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-JZ22VF+MUY-JZ22VF', 'Split AC', 'Inverter', 1.90, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-JR30VF+MUY-JR30VF', 'Split AC', 'Inverter', 2.50, '3 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-JR36VF+MUY-JR36VF', 'Split AC', 'Inverter', 3.00, '2 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-GR18VF+MUY-GR18VF', 'Split AC', 'Inverter', 1.50, '4 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-GR22VF+MUY-GR22VF', 'Split AC', 'Inverter', 1.90, '4 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ13VF+MUY-GZ13VF', 'Split AC', 'Inverter', 1.00, '5 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ18VF+MUY-GZ18VF', 'Split AC', 'Inverter', 1.50, '5 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ22VF+MUY-GZ22VF', 'Split AC', 'Inverter', 1.90, '4 Star'),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ26VF+MUY-GZ26VF', 'Split AC', 'Inverter', 2.20, '4 Star'),
  ('AKABISHI', 'RAM/RBM-AE13VG-X1', 'Split AC', 'Non Inverter', 1.00, '1 Star'),
  ('AKABISHI', 'RAM/RBM-AEH18VG-AA1-X1', 'Split AC', 'Non Inverter', 1.50, '1 Star'),
  ('AKABISHI', 'RAM/RBM-AE22VG-X1', 'Split AC', 'Non Inverter', 1.80, '1 Star'),
  ('AKABISHI', 'RAM/RBM-AE13VG-KT', 'Split AC', 'Non Inverter', 1.00, '1 Star'),
  ('AKABISHI', 'RAM/RBM-AEH18VG-AA1-KT', 'Split AC', 'Non Inverter', 1.50, '1 Star'),
  ('AKABISHI', 'RAM/RBM-AE22VG-KT', 'Split AC', 'Non Inverter', 1.80, '1 Star'),
  ('AKABISHI', 'RAY/RBY-HE13VG-X2', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('AKABISHI', 'RAY/RBY-HE18VG-X1', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('AKABISHI', 'RAY/RBY-HE22VG-X1', 'Split AC', 'Inverter', 1.80, '3 Star'),
  ('AKABISHI', 'RAY/RBY-HE13VG-KT', 'Split AC', 'Inverter', 1.00, '3 Star'),
  ('AKABISHI', 'RAY/RBY-HE18VG-KT', 'Split AC', 'Inverter', 1.50, '3 Star'),
  ('AKABISHI', 'RAY/RBY-HE22VG-KT', 'Split AC', 'Inverter', 1.80, '3 Star'),
  ('AKABISHI', 'EAY/EBY-HA15VG-KT', 'Split AC', 'Inverter', 1.30, '3 Star'),
  ('AKABISHI', 'EAY/EBY-HA19VG-KT', 'Split AC', 'Inverter', 1.60, '3 Star'),
  ('AKABISHI', 'EAY/EBY-HA22VG-KT', 'Split AC', 'Inverter', 1.90, '3 Star'),
  ('AKABISHI', 'EAY/EBY-HA24VG-KT', 'Split AC', 'Inverter', 2.00, '3 Star'),
  ('AKABISHI', 'EAY/EBY-UA13VG-KT', 'Split AC', 'Inverter', 1.00, '5 Star'),
  ('AKABISHI', 'EAY/EBY-UA19VG-KT', 'Split AC', 'Inverter', 1.60, '5 Star'),
  ('AKABISHI', 'EAY/EBY-UA22VG-KT', 'Split AC', 'Inverter', 1.80, '5 Star')
)
INSERT INTO public.ac_models (brand_id, model_number, ac_type, technology, capacity_tons, rating, is_active)
SELECT b.id, s.model_number, s.ac_type, s.technology, s.capacity_tons, s.rating, true
FROM model_seed s
JOIN brand_map b ON b.code = s.brand_code
ON CONFLICT (brand_id, model_number) DO UPDATE SET
  ac_type = EXCLUDED.ac_type,
  technology = EXCLUDED.technology,
  capacity_tons = EXCLUDED.capacity_tons,
  rating = EXCLUDED.rating;

-- 2. Insert Model Variants
WITH model_map AS (
  SELECT m.id AS model_id, b.code AS brand_code, m.model_number
  FROM public.ac_models m
  JOIN public.ac_brands b ON b.id = m.brand_id
),
variant_seed(brand_code, model_number, capacity_tons, capacity_display, star_rating, ac_type, technology, series) AS (
  VALUES
  ('MITSUBISHI_HEAVY', 'SRK / DXK 5CAPDA - W', 1.20, '1.2 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 18CAPDA - W', 1.50, '1.5 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 20CAPDA - W', 1.60, '1.6 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 25CAPDA - W', 2.15, '2.15 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 13YAMDA - W', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 18YAMDA - W', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 21YAMDA - W', 1.75, '1.75 Tr', '3 Star', 'Split AC', 'Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK / DXK 27YAMDA - W', 2.25, '2.25 Tr', '3 Star', 'Split AC', 'Inverter', 'Indian SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK13CRS-S6', 1.10, '1.1 Tr', '2 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK15CXS-W6', 1.30, '1.3 Tr', '2 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK20CXS-W6', 1.60, '1.6 Tr', '3 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK20CSS-S6 / A', 1.60, '1.6 Tr', '3 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK24CW-S6', 1.95, '1.95 Tr', '2 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK25CWX-S6', 1.95, '1.95 Tr', '3 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK25CSS-S6 / A', 2.20, '2.2 Tr', '2 Star', 'Split AC', 'Non Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK13YYM-W6', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK13YXS-W6', 1.10, '1.1 Tr', '5 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK18YXP-W6', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK18YYM-W6', 1.60, '1.6 Tr', '4 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK18YXS2-W6', 1.65, '1.65 Tr', '5 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK20YYM-W6', 1.80, '1.8 Tr', '5 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK24YYM-W6', 2.10, '2.1 Tr', '4 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK24YVS-W6', 2.20, '2.2 Tr', '5 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK100YA-W6', 3.00, '3.0 Tr', '4 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK18YYS-W6 ( WIFII ENABLED )', 1.60, '1.6 Tr', '5 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK24YYS-W6 ( WIFI ENABLED )', 2.20, '2.2 Tr', '5 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK50ZS', 1.50, '1.5 Tr', 'N/A', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK71ZR', 2.10, '2.1 Tr', 'N/A', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('MITSUBISHI_HEAVY', 'SRK100ZR', 3.10, '3.1 Tr', '4 Star', 'Split AC', 'Inverter', 'THAILAND SERIES'),
  ('DAIKIN', 'FTKM35XV', 1.00, '1.0 Tr', '5 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKM50XV', 1.50, '1.5 Tr', '5 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKM60XV', 1.80, '1.8 Tr', '5 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKU35XV', 1.00, '1.0 Tr', '5 Star', 'Split AC', 'Inverter', 'Standard Series - Inverter'),
  ('DAIKIN', 'FTKU42XV', 1.20, '1.2 Tr', '5 Star', 'Split AC', 'Inverter', 'Standard Series - Inverter'),
  ('DAIKIN', 'FTKU50XV', 1.50, '1.5 Tr', '5 Star', 'Split AC', 'Inverter', 'Standard Series - Inverter'),
  ('DAIKIN', 'FTKL35XV', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Premium Series - Inverte', 'Premium Series - Inverte'),
  ('DAIKIN', 'FTKL50XV', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKL60XV', 1.80, '1.8 Tr', '3 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKL71XV', 2.00, '2.0 Tr', '3 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKL90XV', 2.60, '2.6 Tr', '3 Star', 'Split AC', 'Inverter', 'Premium Series - Inverter'),
  ('DAIKIN', 'FTKC35XV', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', 'Standard Series - Inverter'),
  ('DAIKIN', 'FTKC48XV', 1.40, '1.4 Tr', '3 Star', 'Split AC', 'Inverter', 'Standard Series - Inverter'),
  ('DAIKIN', 'FTKC50XV', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', 'Standard Series - Inverter'),
  ('DAIKIN', 'FTQ28XV', 0.80, '0.8 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Standard Series - Non Inverter'),
  ('DAIKIN', 'FTQ30XV', 0.90, '0.9 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Standard Series - Non Inverter'),
  ('DAIKIN', 'FTQ35XV', 1.00, '1.0 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Standard Series - Non Inverter'),
  ('DAIKIN', 'FTQ50XV', 1.50, '1.5 Tr', '2 Star', 'Split AC', 'Non Inverter', 'Standard Series - Non Inverter'),
  ('VOLTAS', 'SAC122 FS EMERALD', 1.00, '1.0 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('VOLTAS', 'SAC182 FS PRISM', 1.50, '1.5 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('VOLTAS', 'SAC242 PLUSH', 2.00, '2.0 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('VOLTAS', 'SAC 123INV VECTRA EMARALD / ELEGANT', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'SAC 183INV VECTRA ZEN / ZENITH SILVER', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'SAC 183INV VERTIS ZENITH GOLD', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'SAC243 INV VECTRA PLUSH', 2.00, '2.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'SAC 125V VECTRA', 1.00, '1.0 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'SAC 185INV VERTIS ELITE', 1.50, '1.5 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'SAC 245 INV VECTRA PLUSH', 2.00, '2.0 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('VOLTAS', 'WAC 122 FS PLATINA-1 ( 22 X 15 )', 1.00, '1.0 Tr', '2 Star', 'Window AC', 'Non Inverter', NULL),
  ('VOLTAS', 'WAC 182 FS PEARL / ELITE ( 26 X 17 )', 1.50, '1.5 Tr', '2 Star', 'Window AC', 'Non Inverter', NULL),
  ('VOLTAS', 'WAC 241 FS PLUS (26 X 17)', 2.00, '2.0 Tr', '1 Star', 'Window AC', 'Non Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ13VF+MU-AGZ13VF', 1.00, '1.0 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ18VF+MU-AGZ18VF', 1.50, '1.5 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ19VF+MU-AGZ19VF', 1.60, '1.6 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MS-AGZ24VF+MU-AGZ24VF', 1.90, '1.9 Tr', '2 Star', 'Split AC', 'Non Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ13VF+MSY-AMZ13VF', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ18VF+MUY-AMZ18VF', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ22VF+MUY-AMZ22VF', 1.90, '1.9 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-AMZ24VF+MUY-AMZ24VF', 2.00, '2.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-JZ13VF+MUY-JZ13VF', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-JZ18VF+MUY-JZ18VF', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-JZ22VF+MUY-JZ22VF', 1.90, '1.9 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-JR30VF+MUY-JR30VF', 2.50, '2.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-JR36VF+MUY-JR36VF', 3.00, '3.0 Tr', '2 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-GR18VF+MUY-GR18VF', 1.50, '1.5 Tr', '4 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-GR22VF+MUY-GR22VF', 1.90, '1.9 Tr', '4 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ13VF+MUY-GZ13VF', 1.00, '1.0 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ18VF+MUY-GZ18VF', 1.50, '1.5 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ22VF+MUY-GZ22VF', 1.90, '1.9 Tr', '4 Star', 'Split AC', 'Inverter', NULL),
  ('MITSUBISHI_ELECTRIC', 'MSY-GZ26VF+MUY-GZ26VF', 2.20, '2.2 Tr', '4 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'RAM/RBM-AE13VG-X1', 1.00, '1.0 Tr', '1 Star', 'Split AC', 'Non Inverter', NULL),
  ('AKABISHI', 'RAM/RBM-AEH18VG-AA1-X1', 1.50, '1.5 Tr', '1 Star', 'Split AC', 'Non Inverter', NULL),
  ('AKABISHI', 'RAM/RBM-AE22VG-X1', 1.80, '1.8 Tr', '1 Star', 'Split AC', 'Non Inverter', NULL),
  ('AKABISHI', 'RAM/RBM-AE13VG-KT', 1.00, '1.0 Tr', '1 Star', 'Split AC', 'Non Inverter', NULL),
  ('AKABISHI', 'RAM/RBM-AEH18VG-AA1-KT', 1.50, '1.5 Tr', '1 Star', 'Split AC', 'Non Inverter', NULL),
  ('AKABISHI', 'RAM/RBM-AE22VG-KT', 1.80, '1.8 Tr', '1 Star', 'Split AC', 'Non Inverter', NULL),
  ('AKABISHI', 'RAY/RBY-HE13VG-X2', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'RAY/RBY-HE18VG-X1', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'RAY/RBY-HE22VG-X1', 1.80, '1.8 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'RAY/RBY-HE13VG-KT', 1.00, '1.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'RAY/RBY-HE18VG-KT', 1.50, '1.5 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'RAY/RBY-HE22VG-KT', 1.80, '1.8 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-HA15VG-KT', 1.30, '1.3 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-HA19VG-KT', 1.60, '1.6 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-HA22VG-KT', 1.90, '1.9 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-HA24VG-KT', 2.00, '2.0 Tr', '3 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-UA13VG-KT', 1.00, '1.0 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-UA19VG-KT', 1.60, '1.6 Tr', '5 Star', 'Split AC', 'Inverter', NULL),
  ('AKABISHI', 'EAY/EBY-UA22VG-KT', 1.80, '1.8 Tr', '5 Star', 'Split AC', 'Inverter', NULL)
)
INSERT INTO public.ac_model_variants (model_id, capacity_tons, capacity_display, star_rating, ac_type, technology, series, source_provenance, is_active)
SELECT mm.model_id, vs.capacity_tons, vs.capacity_display, vs.star_rating, vs.ac_type, vs.technology, vs.series, 'Softwear Data.xlsx', true
FROM variant_seed vs
JOIN model_map mm ON mm.brand_code = vs.brand_code AND mm.model_number = vs.model_number
ON CONFLICT (model_id, capacity_tons, star_rating, ac_type, technology) DO NOTHING;
